// src/ui.js — IslandProcure design system (Glassmorphism 2.0, Sea & Sand)
'use strict';
const IMG = {
  hero: 'https://lh3.googleusercontent.com/aida-public/AB6AXuApWoV0rvqb9QGv2t5RvliGdNnSa1wvALIsiQ4Im2d85ujS9L1sUqIq225CSD66C7Gy532XReAVetLPjH0xdGNQ30QAXEvYUb9NOIQTGT_OrjUzXFv6ukwau5D5CFxgDN9VZAK3zTptji95YAkkzNLHgA-bDQjatEoZo8Ch3dqoRK2y_WZ_nPzojo_ik4WVL7ITLlSd6qWprSiblWI1ILzvnly4CqTbm9PU5doQKvh9aOVI7uK2LQjd',
  choc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXPbE4V7eodpeCuRRgZCUUkAuczYmvsOVlWDwyVghvhAs0SmuzjrLADKo1CBKnvfEHaZ5BYJGUEwGtliZ2ihHfsFBrUK3d85Ois2qi4rdpeMtmFgp-Zl0reraUyCST9TmTIgMtBXMTZ1fTXE2L84k86Rq00tObPyH1ohndlJCGi6Tt25odB-v8KTnJs1gAHFN347KY9dybbR5k-DqQvsF7DajPvyhvX3_3MdXEeTCSy24zL-x-p6Sj',
  coffee: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAft7wG5PpZ6AzQ4tEFW4Vf1s6QfnHMfr1jOS1S2cwNzUFoG6XAyG1iFMBJl-SDI1xuhyx-_hCHxNgsxtnzzQkg8ikA-W6Vr1tab6tLRLk-yJ3EJRQSI51F6FXyHHGBSxCVJkj3f5lcJ6HOxwRFzdAwe8mwVv65DGQRaENcbgRJywMGGlSI7fjeVwTRt6gA5sXZKPZFzHJTNi-xultlw8ObC2-Pyxu5zl6PluTxjcgUGhh7mXf008kD',
  nutmeg: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC3Qnz1Th6Fg7-777HseIazMRJ6Tiza9npcwBYB-3Vx6Tho-tSGem6RXm8-CHCvu9DLzWx4Bdk3kErz2B-icfaDOTMBupiGqRQx7r5Is_PF7oTGE6KBpC6DgfWjmNcR5h_5zrpps39AMD_O0wfVx8WPuqxZ5eknIzXdwraxJKO6rejp5GOV3f7dVtbV12l4d__gaajD65eo0EHKC4hx6qd6VHcV3wLvcuFO1BzR5PvEztEBL61QpYhz',
  seamos: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC6mU0QQH6e8Nxvp-xleZrrnAakgbpw9IEwZx1QrZJ02niQu7ZyaZ9oO1qh8kNAMkF-yw9aam661kv-dLvJbnLb0qlhyZjH544dUgivGLrXzCb_2SoaziDnap3FW6ikEXLK6QAB0dYmuTMelgXe2ByEa5tXRVFZlS14UW-gj9YlCIV9NV25NQ-Bb1pSp1ErqBJQ16IS5TvC70JddVj9kWtxmrFIAlJIixu0SCgYbrIAjCi0N0lQnjrW',
};
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function stateBadge(s){const m={TRADE_VERIFIED:['Verified','verified'],TRANSACTION_VERIFIED:['Transaction Verified','verified'],IDENTITY_VERIFIED:['Identity Verified','verified'],CLAIMED:['Claimed','claimed'],CLAIM_PENDING:['Claim Pending','claimed'],UNCLAIMED_PUBLIC_PROFILE:['Public - Unclaimed','unclaimed']};const l=m[s]||[s,'unclaimed'];return `<span class="state-badge ${l[1]}">${esc(l[0])}</span>`;}

function shell(title, bodyHtml, active) {
  return `<!DOCTYPE html><html lang="en"><head>
<meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>${esc(title)} · Caribbean Trade Network</title>
<link rel="preconnect" href="https://fonts.googleapis.com"/><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Geist:wght@400;500;600;700&family=JetBrains+Mono:wght@400&display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet"/>
<style>
:root{--surface:#f2fbfe;--surface-dim:#d2dcde;--surface-container-lowest:#fff;--surface-container-low:#ecf5f8;--surface-container:#e6eff2;--surface-container-high:#e1eaed;--surface-container-highest:#dbe4e7;--on-surface:#141d1f;--on-surface-variant:#3e494a;--outline:#6f797a;--outline-variant:#bec8ca;--primary:#00535b;--on-primary:#fff;--primary-container:#006d77;--on-primary-container:#9becf7;--secondary:#236863;--on-secondary:#fff;--secondary-container:#a9ece5;--on-secondary-container:#286d67;--tertiary:#5d453e;--gold-1:#FF8C42;--gold-2:#F9C22E;--shadow-soft:0 4px 20px rgba(0,0,0,0.05);--shadow-float:0 20px 40px rgba(0,109,119,0.1)}
*{box-sizing:border-box;margin:0;padding:0}html{scroll-behavior:smooth}
body{font-family:Geist,system-ui,sans-serif;color:var(--on-surface);background:var(--surface-bright);min-height:100vh;overflow-x:hidden;line-height:1.5}
.mesh{position:fixed;inset:0;z-index:-1;opacity:.55;background-image:radial-gradient(at 0% 0%,hsla(184,87%,81%,1) 0px,transparent 50%),radial-gradient(at 100% 0%,hsla(15,80%,75%,1) 0px,transparent 50%),radial-gradient(at 100% 100%,hsla(180,48%,62%,1) 0px,transparent 50%),radial-gradient(at 0% 100%,hsla(20,70%,85%,1) 0px,transparent 50%)}
.glass{backdrop-filter:blur(20px);background:rgba(255,255,255,0.4);border:1px solid rgba(255,255,255,0.5);box-shadow:inset 0 0 20px rgba(255,255,255,0.2);border-radius:1rem}
.glass-float{backdrop-filter:blur(20px);background:rgba(255,255,255,0.5);border:1px solid rgba(255,255,255,0.6);border-radius:1rem;box-shadow:var(--shadow-float)}
.shimmer{position:absolute;inset:0;background:linear-gradient(90deg,transparent,rgba(255,255,255,0.35),transparent);background-size:200% 100%;animation:shimmer 2.4s infinite}@keyframes shimmer{0%{background-position:-200% 0}100%{background-position:200% 0}}
.nav{position:sticky;top:0;z-index:50;background:rgba(255,255,255,0.55);backdrop-filter:blur(24px);border-bottom:1px solid rgba(255,255,255,0.6);box-shadow:var(--shadow-soft)}.nav-inner{max-width:1200px;margin:0 auto;padding:14px 24px;display:flex;align-items:center;justify-content:space-between;gap:24px;flex-wrap:wrap}
.brand{font-weight:700;font-size:22px;letter-spacing:-0.02em;color:var(--primary);display:flex;align-items:center;gap:8px;text-decoration:none}
.nav-links{display:flex;gap:28px;align-items:center}.nav-links a{color:var(--on-surface-variant);text-decoration:none;font-size:14px;font-weight:600;padding:6px 2px;border-bottom:2px solid transparent}.nav-links a:hover{color:var(--primary)}.nav-links a.active{color:var(--primary);border-bottom-color:var(--primary)}.nav-cta{display:flex;gap:12px;align-items:center}
.btn{border:none;border-radius:999px;padding:12px 22px;font-weight:600;font-size:14px;cursor:pointer;text-decoration:none;display:inline-flex;align-items:center;gap:8px;transition:all .2s;line-height:1}.btn-primary{background:var(--primary);color:var(--on-primary);box-shadow:var(--shadow-soft)}.btn-primary:hover{background:var(--primary-container);color:var(--on-primary-container);transform:translateY(-1px)}.btn-glass{background:rgba(255,255,255,0.5);color:var(--primary);border:1px solid rgba(255,255,255,0.6);backdrop-filter:blur(8px)}.btn-glass:hover{background:rgba(255,255,255,0.85)}.btn-gold{background:linear-gradient(90deg,var(--gold-1),var(--gold-2));color:#fff}.btn-block{width:100%;justify-content:center}
.wrap{max-width:1200px;margin:0 auto;padding:0 24px}main{flex:1}
.hero{position:relative;min-height:76vh;display:flex;align-items:center;justify-content:center;padding:110px 24px 60px;overflow:hidden}.hero-bg{position:absolute;inset:0;z-index:-1}.hero-img{position:absolute;inset:0;background-size:cover;background-position:center;mix-blend-mode:overlay;opacity:.45}.hero-grad{position:absolute;inset:0;background:linear-gradient(to bottom,rgba(242,251,254,0.2),rgba(242,251,254,0.92))}.hero-card{max-width:860px;margin:0 auto;text-align:center;padding:48px 40px;position:relative}
.hero-eyebrow{display:inline-flex;align-items:center;gap:8px;color:var(--secondary);font-size:13px;font-weight:600;letter-spacing:.06em;text-transform:uppercase;margin-bottom:16px}h1{font-size:clamp(34px,6vw,52px);font-weight:700;letter-spacing:-0.03em;color:var(--primary);line-height:1.05;margin-bottom:16px}.hero-sub{font-size:18px;color:var(--on-surface-variant);max-width:640px;margin:0 auto 28px;line-height:1.5}.hero-actions{display:flex;flex-direction:column;gap:14px;align-items:center}@media(min-width:640px){.hero-actions{flex-direction:row;justify-content:center}}
.section{max-width:1200px;margin:0 auto;padding:56px 24px}.section-head{text-align:center;max-width:720px;margin:0 auto 40px}.section-head h2{font-size:32px;font-weight:600;letter-spacing:-0.02em;color:var(--primary);margin-bottom:10px}.section-head p{color:var(--on-surface-variant);font-size:16px}
.bento{display:grid;grid-template-columns:1fr;gap:16px}@media(min-width:768px){.bento{grid-template-columns:repeat(12,1fr)}}.bento .glass{padding:24px;position:relative;overflow:hidden}.bento-8{grid-column:span 12}@media(min-width:768px){.bento-8{grid-column:span 8}}.bento-4{grid-column:span 12}@media(min-width:768px){.bento-4{grid-column:span 4}}.bento-kicker{display:flex;align-items:center;gap:8px;color:var(--secondary);font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:.08em;margin-bottom:10px}.bento-kicker .ms{font-size:20px}.bento h3{font-size:22px;font-weight:600;color:var(--on-surface);margin-bottom:8px}.bento h3 .hl{color:var(--primary)}.bento p{color:var(--on-surface-variant);font-size:15px}.big-num{font-size:52px;font-weight:700;color:var(--primary);letter-spacing:-0.04em;line-height:1}.mono{font-family:'JetBrains Mono',monospace;font-size:13px;color:var(--outline)}.bento-icon{position:absolute;right:-10px;bottom:-10px;opacity:.1;pointer-events:none}.bento-icon .ms{font-size:140px;color:var(--primary)}
.pgrid{display:grid;grid-template-columns:1fr;gap:16px}@media(min-width:640px){.pgrid{grid-template-columns:repeat(2,1fr)}}@media(min-width:1024px){.pgrid{grid-template-columns:repeat(4,1fr)}}.pcard{overflow:hidden;transition:transform .25s;display:flex;flex-direction:column}.pcard:hover{transform:translateY(-4px)}.pimg{height:160px;background-size:cover;background-position:center;position:relative;background-color:var(--surface-container-high)}.pbadge{position:absolute;top:12px;left:12px;background:linear-gradient(90deg,var(--gold-1),var(--gold-2));color:#fff;padding:5px 12px;border-radius:999px;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:.06em;display:flex;align-items:center;gap:5px;box-shadow:var(--shadow-soft);overflow:hidden}.pbody{padding:20px;display:flex;flex-direction:column;flex:1}.pbody h4{font-size:20px;font-weight:600;color:var(--on-surface);margin-bottom:4px}.pbody .pcat{color:var(--on-surface-variant);font-size:14px;margin-bottom:12px}.pbody .pmeta{color:var(--outline);font-size:13px;margin-bottom:12px}.passport{display:inline-flex;align-items:center;gap:6px;color:var(--primary);font-size:13px;font-weight:600;text-decoration:none;margin-top:auto;padding-top:12px}.passport:hover{color:var(--primary-container)}
.dir{display:grid;grid-template-columns:1fr;gap:16px}@media(min-width:700px){.dir{grid-template-columns:repeat(2,1fr)}}@media(min-width:1024px){.dir{grid-template-columns:repeat(3,1fr)}}.bcard{padding:22px;display:flex;flex-direction:column;gap:8px}.bcard h3{font-size:18px;font-weight:600;color:var(--on-surface)}.bcard .bloc{color:var(--on-surface-variant);font-size:14px;display:flex;align-items:center;gap:6px}.bcard .bdisclaimer{font-size:13px;font-style:italic;color:var(--on-surface-variant);opacity:.85;margin-top:6px}.state-badge{display:inline-block;padding:3px 10px;border-radius:999px;font-size:11px;font-weight:600;width:fit-content}.state-badge.verified{background:rgba(35,104,99,.15);color:var(--secondary)}.state-badge.claimed{background:rgba(117,93,84,.15);color:var(--tertiary)}.state-badge.unclaimed{background:rgba(0,83,91,.12);color:var(--primary)}
.form{max-width:560px;margin:0 auto;padding:28px;display:grid;gap:14px}label{font-size:13px;font-weight:600;color:var(--on-surface-variant)}input,select,textarea{width:100%;padding:12px 14px;border-radius:8px;border:1px solid var(--outline-variant);background:rgba(255,255,255,0.6);color:var(--on-surface);font:inherit;transition:all .2s}input:focus,select:focus,textarea:focus{outline:none;border-color:var(--primary-container);box-shadow:0 0 0 3px rgba(0,109,119,.15);background:rgba(255,255,255,0.9)}
table{width:100%;border-collapse:collapse;margin-top:12px}th,td{text-align:left;padding:10px 12px;border-bottom:1px solid var(--outline-variant);font-size:14px}th{color:var(--on-surface-variant);font-size:12px;text-transform:uppercase;letter-spacing:.06em}
footer{margin-top:48px;background:var(--surface-container-lowest);border-top:1px solid rgba(190,200,202,0.3)}.foot{max-width:1200px;margin:0 auto;padding:48px 24px;display:flex;flex-direction:column;gap:24px;justify-content:space-between}@media(min-width:768px){.foot{flex-direction:row;align-items:center}}.foot .brand{font-size:20px;margin-bottom:4px}.foot .copy{color:var(--on-surface-variant);font-size:14px}.foot-links{display:flex;gap:24px;flex-wrap:wrap}.foot-links a{color:var(--on-surface-variant);text-decoration:none;font-size:14px;font-weight:600}.foot-links a:hover{color:var(--primary)}
.ms{font-family:'Material Symbols Outlined';font-weight:normal;font-style:normal;display:inline-block;line-height:1;letter-spacing:normal;text-transform:none;vertical-align:middle;-webkit-font-smoothing:antialiased}
</style></head><body>
<div class="mesh"></div>
<nav class="nav"><div class="nav-inner">
<a class="brand" href="/"><span class="ms" style="color:var(--primary-container);font-variation-settings:'FILL' 1">public</span> Caribbean Trade</a>
<div class="nav-links">
<a href="/" class="${active==='/'?'active':''}">Marketplace</a><a href="/browse" class="${active==='/browse'?'active':''}">Directory</a><a href="/sourcing" class="${active==='/sourcing'?'active':''}">Sourcing</a><a href="/landed-cost" class="${active==='/landed-cost'?'active':''}">Landed Cost</a><a href="/trade-info" class="${active==='/trade-info'?'active':''}">Trade Info</a><a href="/plans" class="${active==='/plans'?'active':''}">Plans</a>
</div>
<div class="nav-cta">${active?`<a class="btn btn-glass" href="/logout">${esc(active)}</a>`:`<a class="btn btn-glass" href="/login">Sign in</a><a class="btn btn-primary" href="/signup">Get Started</a>`}</div>
</div></nav>
<main>${bodyHtml}</main>
<footer><div class="foot">
<div><div class="brand"><span class="ms" style="color:var(--primary-container);font-variation-settings:'FILL' 1">public</span> Caribbean Trade</div><p class="copy">© ${new Date().getFullYear()} Caribbean AI Trade Network. All rights reserved.</p></div>
<div class="foot-links"><a href="/browse">Logistics Network</a><a href="/trade-info">Trade Hub Stats</a><a href="/plans">Digital Passports</a><a href="/privacy">Privacy Policy</a></div>
</div></footer></body></html>`;
}

function marketplace(biz, products) {
  const body = `
  <section class="hero"><div class="hero-bg"><div class="hero-img" style="background-image:url('${IMG.hero}')"></div><div class="hero-grad"></div></div>
    <div class="glass-float hero-card">
      <div class="hero-eyebrow"><span class="ms" style="font-variation-settings:'FILL' 1">public</span> The New Caribbean Value Chain</div>
      <h1>Beyond commodities.<br/>A $6.5B digital trade ecosystem.</h1>
      <p class="hero-sub">Find, verify, and trade across the Caribbean — and sell to global buyers. Powered by value-added sovereignty.</p>
      <form method="get" action="/search" style="display:flex;gap:10px;max-width:560px;margin:0 auto 20px;flex-wrap:wrap">
        <input name="q" placeholder="Find eco-certified cocoa suppliers in Grenada…" style="flex:1;min-width:220px"/>
        <button class="btn btn-primary" type="submit"><span class="ms" style="font-variation-settings:'FILL' 1">search</span> Explore</button>
      </form>
      <div class="hero-actions">
        <a class="btn btn-primary" href="/sourcing"><span class="ms" style="font-variation-settings:'FILL' 1">explore</span> Post a Sourcing Request</a>
        <a class="btn btn-glass" href="/browse"><span class="ms">analytics</span> View the Directory</a>
        <a class="btn btn-glass" href="/signup?role=buyer_external"><span class="ms" style="font-variation-settings:'FILL' 1">public</span> Global Buyers</a>
      </div>
    </div>
  </section>
  <section class="section"><div class="section-head"><h2>Economic Evolution</h2><p>Pivoting from raw materials to high-margin, specialized exports via the CARICOM Digital Single Market.</p></div>
    <div class="bento">
      <div class="glass bento-8"><div class="bento-icon"><span class="ms" style="font-variation-settings:'FILL' 1">account_tree</span></div>
        <div class="bento-kicker"><span class="ms" style="font-variation-settings:'FILL' 1">trending_up</span> Value-Chain Integration</div>
        <h3>Craft chocolate margins have increased by <span class="hl">400%</span> vs bulk beans.</h3>
        <p>Producers in Trinidad &amp; Tobago and Grenada are leading the transition from raw export to premium finished goods.</p></div>
      <div class="glass bento-4"><div class="bento-icon"><span class="ms" style="font-variation-settings:'FILL' 1">shopping_cart</span></div>
        <div class="bento-kicker" style="color:var(--tertiary)"><span class="ms" style="font-variation-settings:'FILL' 1">public</span> Digital Market</div>
        <div class="big-num">$6.5B</div><p>E-commerce revenue reached by end of 2025 via DTC exports.</p></div>
      <div class="glass bento-4"><div class="bento-kicker"><span class="ms" style="font-variation-settings:'FILL' 1">liquor</span> Premium Spirits</div>
        <h3>Caribbean rum exports hit a record <span class="hl">$1.8B</span> valuation.</h3>
        <p class="mono" style="border-top:1px solid var(--outline-variant);padding-top:12px;margin-top:10px">Rivaling single malt scotch in global auctions.</p></div>
      <div class="glass bento-8"><div class="bento-kicker"><span class="ms" style="font-variation-settings:'FILL' 1">local_shipping</span> Logistics Efficiency</div>
        <h3><span class="hl">30% improvement</span> in last-mile delivery.</h3>
        <p>Powered by localized hub-and-spoke models, reducing cross-border friction.</p></div>
    </div>
  </section>
  <section class="section"><div class="section-head"><h2>High-Value Niche Exports</h2><p>Explore authenticated premium products driving the region's digital economy.</p></div>
    <div class="pgrid">${products.length ? products.map(p => `<div class="glass pcard"><div class="pimg" style="background-image:url('${p.img||IMG[p.key]||IMG.choc}')"><div class="pbadge"><span class="ms" style="font-variation-settings:'FILL' 1">verified</span> Verified Origin</div></div><div class="pbody"><h4>${esc(p.name)}</h4><p class="pcat">${esc(p.category||'')}</p><p class="pmeta">${esc(p.country||'Caribbean')}${p.price?` · US$${p.price}`:''}</p><a class="passport" href="/browse"><span class="ms">qr_code_scanner</span> Digital Passport</a></div></div>`).join('') : `
      <div class="glass pcard"><div class="pimg" style="background-image:url('${IMG.choc}')"><div class="pbadge"><span class="ms" style="font-variation-settings:'FILL' 1">verified</span> Verified Origin</div></div><div class="pbody"><h4>Grenada Craft Chocolate</h4><p class="pcat">Food &amp; Beverage</p><p class="pmeta">Grenada</p><a class="passport" href="/browse"><span class="ms">qr_code_scanner</span> Digital Passport</a></div></div>
      <div class="glass pcard"><div class="pimg" style="background-image:url('${IMG.coffee}')"><div class="pbadge"><span class="ms" style="font-variation-settings:'FILL' 1">verified</span> Verified Origin</div></div><div class="pbody"><h4>Jamaican Blue Mountain</h4><p class="pcat">Coffee</p><p class="pmeta">Jamaica</p><a class="passport" href="/browse"><span class="ms">qr_code_scanner</span> Digital Passport</a></div></div>
      <div class="glass pcard"><div class="pimg" style="background-image:url('${IMG.nutmeg}')"><div class="pbadge"><span class="ms" style="font-variation-settings:'FILL' 1">verified</span> Verified Origin</div></div><div class="pbody"><h4>Trinidadian Nutmeg Oils</h4><p class="pcat">Beauty &amp; Wellness</p><p class="pmeta">Trinidad &amp; Tobago</p><a class="passport" href="/browse"><span class="ms">qr_code_scanner</span> Digital Passport</a></div></div>
      <div class="glass pcard"><div class="pimg" style="background-image:url('${IMG.seamos}')"><div class="pbadge"><span class="ms" style="font-variation-settings:'FILL' 1">verified</span> Verified Origin</div></div><div class="pbody"><h4>St. Lucian Sea Moss</h4><p class="pcat">Caribbean Wellness</p><p class="pmeta">Saint Lucia</p><a class="passport" href="/browse"><span class="ms">qr_code_scanner</span> Digital Passport</a></div></div>`}
    </div>
  </section>
  <section class="section" style="text-align:center"><h2 style="color:var(--primary);font-size:32px;font-weight:600;letter-spacing:-0.02em">${biz.length} businesses across the Caribbean</h2><p style="color:var(--on-surface-variant);max-width:560px;margin:12px auto 24px">Source-backed supplier profiles with explicit verification — unclaimed, claimed, and trade-verified.</p><a class="btn btn-primary" href="/browse">Browse the Directory</a></section>`;
  return shell('Marketplace', body, '/');
}
function directory(list) {
  const body = `<section class="section"><div class="section-head"><h2>Business Directory</h2><p>Source-backed profiles across the Caribbean. Unclaimed profiles are clearly labeled and never presented as verified.</p></div>
  <div class="dir">${list.map(b=>`<div class="glass bcard"><div style="display:flex;justify-content:space-between;align-items:flex-start;gap:8px"><h3>${esc(b.name)}</h3>${stateBadge(b.state)}</div><div class="bloc"><span class="ms" style="font-size:16px">place</span>${esc(b.country)}${b.city?' · '+esc(b.city):''}</div><div class="bloc"><span class="ms" style="font-size:16px">category</span>${esc(b.category||'uncategorized')}</div>${b.disclaimer?`<div class="bdisclaimer">${esc(b.disclaimer)}</div>`:''}<div class="mono">${b.id}</div></div>`).join('')||'<p>No businesses yet.</p>'}</div></section>`;
  return shell('Business Directory', body, '/browse');
}
function sourcing(rfqs) {
  const body = `<section class="section"><div class="section-head"><h2>Post a Sourcing Request</h2><p>Tell us what you need, where it's going, and by when. Verified suppliers respond with quotes.</p></div>
  <form class="glass form" method="post" action="/api/rfqs"><div><label>Your name</label><input name="buyer_name" required/></div><div><label>Email</label><input name="buyer_email" required/></div><div><label>Product / what you need</label><input name="product" required placeholder="e.g. craft chocolate, blue mountain coffee, nutmeg oil…"/></div><div><label>Quantity</label><input name="quantity" type="number" min="1"/></div><div><label>Destination country</label><input name="destination_country" placeholder="e.g. US, Canada, UK, Barbados"/></div><div><label>Deadline</label><input name="deadline" type="date"/></div><div><label>Notes</label><textarea name="notes" rows="3"></textarea></div><button class="btn btn-primary" type="submit"><span class="ms" style="font-variation-settings:'FILL' 1">send</span> Submit Sourcing Request</button></form>
  <div class="section-head" style="margin-top:56px"><h2>Open Requests</h2></div><div class="glass" style="padding:24px;overflow-x:auto"><table><tr><th>Product</th><th>Qty</th><th>Destination</th><th>Status</th></tr>${rfqs.map(r=>`<tr><td>${esc(r.product)}</td><td>${r.quantity}</td><td>${esc(r.destination_country||'-')}</td><td>${esc(r.status)}</td></tr>`).join('')||'<tr><td colspan="4">No open requests yet.</td></tr>'}</table></div></section>`;
  return shell('Sourcing / RFQ', body, '/sourcing');
}
function landedCostPage() {
  const body = `<section class="section"><div class="section-head"><h2>Estimate True Delivered Cost</h2><p>A deterministic engine — every component shown, no hidden arithmetic.</p></div>
  <form class="glass form" method="get" action="/api/landed-cost"><div><label>Product value (USD)</label><input name="product_value" type="number" value="100"/></div><div><label>Origin charges (USD)</label><input name="origin_charges" type="number" value="5"/></div><div><label>Freight (USD)</label><input name="freight" type="number" value="20"/></div><div><label>Insurance (USD)</label><input name="insurance" type="number" value="5"/></div><div><label>Duty (USD)</label><input name="applicable_duty" type="number" value="0"/></div><div><label>Taxes &amp; levies (USD)</label><input name="taxes_and_levies" type="number" value="0"/></div><div><label>Destination port charges (USD)</label><input name="destination_port_charges" type="number" value="10"/></div><div><label>Brokerage (USD)</label><input name="brokerage" type="number" value="15"/></div><div><label>Inland delivery (USD)</label><input name="inland_delivery" type="number" value="10"/></div><button class="btn btn-primary" type="submit"><span class="ms" style="font-variation-settings:'FILL' 1">calculate</span> Calculate</button></form></section>`;
  return shell('Landed Cost Estimator', body, '/landed-cost');
}
function tradeInfoPage() {
  const body = `<section class="section"><div class="section-head"><h2>Trade Requirements &amp; Knowledge</h2><p>Decision-support only. Confirm with the relevant authority before relying on any rule.</p></div>
  <form class="glass form" method="get" action="/api/trade/requirements"><div><label>Origin (Caribbean island)</label><input name="origin" placeholder="e.g. Jamaica"/></div><div><label>Destination country</label><input name="destination" placeholder="e.g. US"/></div><div><label>Category</label><input name="category" placeholder="e.g. food_beverage"/></div><div><label>HS code (optional)</label><input name="hs" placeholder="e.g. 1806"/></div><button class="btn btn-primary" type="submit"><span class="ms" style="font-variation-settings:'FILL' 1">verified</span> Check Requirements</button></form></section>`;
  return shell('Trade Information', body, '/trade-info');
}
function plansPage(active) {
  const plans = [
    {slug:'free',name:'Free',price:'$0',cycle:'forever',features:['Public directory presence','Claim one business','10 product listings','Buyer RFQ access'],cta:'Start Free'},
    {slug:'pro',name:'Pro',price:'$44',cycle:'/month',features:['Up to 3 businesses','100 products','Quote & sell to RFQs','Order management','AI quote assistant','Remove platform branding'],cta:'Choose Pro'},
    {slug:'trade',name:'Trade',price:'$149',cycle:'/month',features:['Unlimited businesses','Unlimited products','Multi-currency & FX','Dedicated account manager','API access','Verified trade badge priority'],cta:'Choose Trade'},
  ];
  const body = `<section class="section"><div class="section-head"><h2>Simple Plans. Free to Start.</h2><p>Free directory + RFQ access for everyone. Paid upgrades unlock selling, quoting and advanced trade tools.</p></div>
  <div class="pgrid" style="grid-template-columns:repeat(auto-fit,minmax(280px,1fr))">${plans.map(p=>`<div class="glass pcard" style="padding:28px"><h3 style="font-size:20px;font-weight:600;color:var(--primary)">${p.name}</h3><div style="font-size:42px;font-weight:700;color:var(--on-surface);letter-spacing:-0.03em;margin:8px 0 2px">${p.price}<span style="font-size:14px;color:var(--on-surface-variant)">${p.cycle==='forever'?' forever':p.cycle}</span></div><ul style="list-style:none;padding:16px 0 0;display:grid;gap:10px">${p.features.map(f=>`<li style="display:flex;gap:8px;align-items:flex-start"><span class="ms" style="color:var(--secondary);font-variation-settings:'FILL' 1">check_circle</span><span style="color:var(--on-surface-variant);font-size:14px">${esc(f)}</span></li>`).join('')}</ul><a class="btn ${p.slug==='free'?'btn-primary':'btn-gold'} btn-block" style="margin-top:20px" href="/signup?plan=${p.slug}">${p.cta}</a></div>`).join('')}</div></section>`;
  return shell('Plans', body, '/plans');
}
function loginPage(active) {
  const body = `<section class="section"><div class="glass form" style="max-width:440px"><div class="section-head" style="margin:0 0 20px"><h2>Sign in</h2><p>Access your trade workspace.</p></div><form method="post" action="/api/login" style="display:grid;gap:14px"><div><label>Email</label><input name="email" required/></div><div><label>Password</label><input name="password" type="password" required/></div><button class="btn btn-primary btn-block" type="submit">Sign in</button></form></div></section>`;
  return shell('Sign in', body, active);
}
function signupPage(active, role) {
  const body = `<section class="section"><div class="glass form" style="max-width:460px"><div class="section-head" style="margin:0 0 20px"><h2>Start Free</h2><p>${role==='buyer_external'?'For global &amp; diaspora buyers sourcing Caribbean-origin goods.':'Free directory + RFQ access. Upgrade anytime.'}</p></div><form method="post" action="/api/register" style="display:grid;gap:14px"><input type="hidden" name="buyer_external" value="${role==='buyer_external'?'true':''}"/><div><label>Name</label><input name="name" required/></div><div><label>Email</label><input name="email" required/></div><div><label>Company (optional)</label><input name="org_name"/></div><div><label>Password (8+ chars)</label><input name="password" type="password" required/></div><div><label>Island / currency</label><select name="island"><option value="tt">Trinidad &amp; Tobago (TTD)</option><option value="jm">Jamaica (JMD)</option><option value="bb">Barbados (BBD)</option><option value="gy">Guyana (GYD)</option><option value="us">United States (USD)</option><option value="ca">Canada (CAD)</option><option value="gb">United Kingdom (GBP)</option></select></div><div><label>Role</label><select name="role"><option value="buyer">Buyer</option><option value="supplier">Supplier</option></select></div><button class="btn btn-primary btn-block" type="submit">Create Free Account</button></form></div></section>`;
  return shell('Start Free', body, active);
}
module.exports = { shell, esc, IMG, marketplace, directory, sourcing, landedCostPage, tradeInfoPage, plansPage, loginPage, signupPage };
