-- ANALYTICS SCHEMA
create table if not exists public.page_views (
  id uuid default uuid_generate_v4() primary key,
  path text not null,
  user_id uuid references public.profiles(id),
  ip_address text, -- Note: client-side collection of IP is tricky with basic Supabase, might need edge function. We'll skip or store null for now.
  user_agent text,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.page_views enable row level security;

create policy "Anyone can insert page views"
  on public.page_views for insert
  with check (true);

create policy "Admins can view analytics"
  on public.page_views for select
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role in ('admin', 'super_admin')
    )
  );

-- ADS ENGINE SCHEMA
create table if not exists public.ad_campaigns (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  client text, -- Could be a user reference, but text is fine for internal use
  status text default 'draft', -- 'active', 'paused', 'draft', 'ended'
  type text not null, -- 'CPC', 'CPM', 'CPA'
  budget decimal(10,2) default 0,
  spent decimal(10,2) default 0,
  impressions integer default 0,
  clicks integer default 0,
  conversions integer default 0,
  placements text[], -- Array of strings e.g. ['homepage', 'search']
  start_date date,
  end_date date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.ad_campaigns enable row level security;

create policy "Admins can manage campaigns"
  on public.ad_campaigns for all
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role in ('admin', 'super_admin')
    )
  );

-- SITE ALERTS SCHEMA
create table if not exists public.site_alerts (
  id text primary key, -- Use text ID as generated by service 'alert_' + timestamp
  category text,
  severity text,
  title text,
  message text,
  details jsonb,
  auto_fixable boolean default false,
  fix_applied boolean default false,
  fix_result text,
  status text default 'new',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  resolved_at timestamp with time zone
);

alter table public.site_alerts enable row level security;

create policy "Admins can manage alerts"
  on public.site_alerts for all
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role in ('admin', 'super_admin')
    )
  );
